export const data = [
  {
    title: "Stopwatch",
    desc: "A simple stopwatch application.",
    github: "https://github.com/shekhawatbhawani/Stop-Random-Color",
    live: "https://stopwatch-alpha-one.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?stopwatch",
  },
  {
    title: "Counter",
    desc: "A counter application with increment and decrement functionality.",
    github: "https://github.com/shekhawatbhawani/Counter",
    live: "https://counter-nu-sooty.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?counter",
  },
  {
    title: "Age Calculator",
    desc: "An age calculator that calculates your age based on your birthdate.",
    github: "https://github.com/shekhawatbhawani/Age-Calculator",
    live: "https://age-calculator-phi-one.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?calculator",
  },
  {
    title: "Calender",
    desc: "A dynamic calendar that displays the current month's dates.",
    github: "https://github.com/shekhawatbhawani/Calender",
    live: "https://calender-eight-puce.vercel.app/",
  
  },
  {
    title: "Color Switcher",
    desc: "A color switcher that changes the background color when clicked.",
    github: "https://github.com/shekhawatbhawani/Color-Switcher",
    live: "https://color-switcher-psi.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?colors",
  },
  {
    title: "Covid-19 API",
    desc: "An API-based project showing COVID-19 statistics.",
    github: "https://github.com/shekhawatbhawani/covid-19-API",
    live: "https://covid-19-api-eta.vercel.app/",
    
  },
  {
    title: "Hindi Random Jokes",
    desc: "A web app that displays random jokes in Hindi.",
    github: "https://github.com/shekhawatbhawani/Hindi-Random-Joke",
    live: "https://hindi-random-jokes.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?jokes",
  },
  {
    title: "Frontend Practice",
    desc: "A project for practicing frontend development skills.",
    github: "https://github.com/shekhawatbhawani/Frontend-Practice",
    live: "https://frontend-practice-lime.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?frontend",
  },
  {
    title: "Number Guessing Game",
    desc: "A game where users try to guess a random number.",
    github: "https://github.com/shekhawatbhawani/Number-Guessing-Game-",
    live: "https://number-guessing-game-nu-rouge.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?numbers",
  },
  {
    title: "Highlight Word",
    desc: "A web app that highlights a word in a paragraph.",
    github: "https://github.com/shekhawatbhawani/Highlight-Word",
    live: "https://highlight-word.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?highlight",
  },
  {
    title: "Interest Calculator",
    desc: "An app that calculates interest on a given amount.",
    github: "https://github.com/shekhawatbhawani/Interest-Calculator",
    live: "https://interest-calculator-gilt.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?interest",
  },
  {
    title: "Linear Search",
    desc: "A simple linear search algorithm implemented in JavaScript.",
    github: "https://github.com/shekhawatbhawani/Linear-Search-",
    live: "https://linear-search-ten.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?search",
  },
  {
    title: "Mark Sheet",
    desc: "A web app that displays a student's marksheet.",
    github: "https://github.com/shekhawatbhawani/Mark-Sheet-",
    live: "https://mark-sheet-six.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?marksheet",
  },
  {
    title: "My Quiz Web",
    desc: "A quiz web app with multiple questions and answers.",
    github: "https://github.com/shekhawatbhawani/My-Quiz-Web-",
    live: "https://my-quiz-web.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?quiz",
  },
  {
    title: "Number Filter",
    desc: "An app that filters out numbers based on user input.",
    github: "https://github.com/shekhawatbhawani/Number-Filter",
    live: "https://number-filter-livid.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?filter",
  },
  {
    title: "Profile Statics",
    desc: "A profile statistics web app showing user data.",
    github: "https://github.com/shekhawatbhawani/Profile-Statics",
    live: "https://profile-statics.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?profile",
  },
  {
    title: "Random Color",
    desc: "A web app that generates a random color.",
    github: "https://github.com/shekhawatbhawani/Random-Color-",
    live: "https://random-color-pearl.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?random",
  },
  {
    title: "Random Paragraph Generator",
    desc: "An app that generates a random paragraph.",
    github: "https://github.com/shekhawatbhawani/Random-Paragraph-Generate",
    live: "https://random-paragraph-generate.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?paragraph",
  },
  {
    title: "Random Password Generator",
    desc: "A web app to generate random passwords.",
    github: "https://github.com/shekhawatbhawani/Random-Password-",
    live: "https://random-password-chi.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?password",
  },
  {
    title: "Real-time Character Counter",
    desc: "A real-time character counter for text input.",
    github: "https://github.com/shekhawatbhawani/Real-time-Character-Counter",
    live: "https://real-time-character-counter-eight.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?counter",
  },
  {
    title: "Stop Random Color",
    desc: "A web app that stops the random color change on click.",
    github: "https://github.com/shekhawatbhawani/Stop-Random-Color",
    live: "https://stop-random-color.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?color",
  },
  {
    title: "Temperature Converter",
    desc: "An app that converts temperatures between Celsius and Fahrenheit.",
    github: "https://github.com/shekhawatbhawani/Temperature-Convert",
    live: "https://temperature-convert-woad.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?temperature",
  },
  {
    title: "Travel Website",
    desc: "A travel website displaying popular destinations.",
    github: "https://github.com/shekhawatbhawani/Trevels-Website",
    live: "https://trevels-website.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?travel",
  },
  {
    title: "Tip Calculator",
    desc: "An app that calculates tips based on the bill amount.",
    github: "https://github.com/shekhawatbhawani/Tip-Calculator",
    live: "https://tip-calculator-ten-ochre.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?calculator",
  },
  {
    title: "Digital Clock",
    desc: "A digital clock web app.",
    github: "https://github.com/shekhawatbhawani/Digital-Clock",
    live: "https://digital-clock-xi-eight.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?clock",
  },
  {
    title: "Dictionary",
    desc: "A dictionary web app for looking up word meanings.",
    github: "https://github.com/shekhawatbhawani/Dictionary",
    live: "https://dictionary-eight-smoky.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?dictionary",
  },
  {
    title: "Note App",
    desc: "A simple note-taking app.",
    github: "https://github.com/shekhawatbhawani/Note-App",
    live: "https://note-app-six-ochre.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?notes",
  },

  {
    title: "Pomodoro Timer",
    desc: "A Pomodoro timer for productivity.",
    github: "https://github.com/shekhawatbhawani/Pomodoro-Timer",
    live: "https://pomodoro-timer-sigma-ashy.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?pomodoro",
  },
  {
    title: "Currency Converter",
    desc: "An app for converting currencies.",
    github: "https://github.com/shekhawatbhawani/Currency-Converter",
    live: "https://currency-converter-eta-six.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?currency",
  },
  {
    title: "Loading Animation",
    desc: "A web page that shows a loading animation.",
    github: "https://github.com/shekhawatbhawani/Loading",
    live: "https://loading-ten-liart.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?loading",
  },
  {
    title: "Calculator",
    desc: "A simple calculator app.",
    github: "https://github.com/shekhawatbhawani/Calculator",
    live: "https://calculator-seven-woad-57.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?calculator",
  },
  {
    title: "Todos List",
    desc: "A to-do list web app to track tasks.",
    github: "https://github.com/shekhawatbhawani/Todos-List",
    live: "https://todos-list-beta.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?todos",
  },
  {
    title: "Github API",
    desc: "A web app that integrates with GitHub's API.",
    github: "https://github.com/shekhawatbhawani/Github-API",
    live: "https://github-api-wheat-nine.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?github",
  },
  {
    title: "Dark Mood",
    desc: "A website that toggles between dark and light modes.",
    github: "https://github.com/shekhawatbhawani/Dark_mood-",
    live: "https://dark-mood-kohl.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?dark-mode",
  },
  {
    title: "Type Writer",
    desc: "A typewriter effect web app.",
    github: "https://github.com/shekhawatbhawani/Type-writer",
    live: "https://type-writer-orcin.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?typewriter",
  },
  {
    title: "Type Writer 2",
    desc: "Another typewriter effect web app with enhanced features.",
    github: "https://github.com/shekhawatbhawani/Type-writer-xa85",
    live: "https://type-writer-xa85.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?typewriter",
  },
  {
    title: "Weather App (JS)",
    desc: "A weather app using JavaScript to show weather forecasts.",
    github: "https://github.com/shekhawatbhawani/Weather-App-Using-JS",
    live: "https://weather-app-using-js-ten.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?weather",
  },
  {
    title: "Expense Tracker (JS)",
    desc: "An expense tracker built using JavaScript.",
    github: "https://github.com/shekhawatbhawani/Expense-Tracker-Using-JS",
    live: "https://expense-tracke-ten.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?expense",
  },
  {
    title: "Form Edit (React)",
    desc: "A React app that allows users to edit forms.",
    github: "https://github.com/shekhawatbhawani/Form-Edit-using-react-",
    live: "https://form-edit-using-react.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?form",
  },
  {
    title: "Expense Tracker (React)",
    desc: "A React app for tracking expenses.",
    github: "https://github.com/shekhawatbhawani/Expense-Tracker-Using-React",
    live: "https://expense-tracker-using-react-psi.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?expense",
  },
  {
    title: "Weather App (React)",
    desc: "A weather app built with React to display weather information.",
    github: "https://github.com/shekhawatbhawani/Weather-App-Using-React",
    live: "https://weather-app-using-react-nine.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?weather",
  },
  {
    title: "Todo App (React)",
    desc: "A to-do app built with React.",
    github: "https://github.com/shekhawatbhawani/Todo-App-React",
    live: "https://todo-app-react-xi-nine.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?todo",
  },
  {
    title: "Job App",
    desc: "A job application form with various features.",
    github: "https://github.com/shekhawatbhawani/Job-App-",
    live: "https://job-app-steel-eta.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?job",
  },
  {
    title: "Portfolio",
    desc: "My personal portfolio showcasing my skills and projects.",
    github: "https://github.com/shekhawatbhawani/My-Portfoliyo",
    live: "https://my-portfoliyo-lyart.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?portfolio",
  },
  {
    title: "Food Website",
    desc: "A food website displaying various food items.",
    github: "https://github.com/shekhawatbhawani/Food-Website-",
    live: "https://food-website-eight-opal.vercel.app/",
    img: "https://source.unsplash.com/random/400x300/?food",
  },
];

export const projectImages = [
  "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
  "https://images.unsplash.com/photo-1519125323398-675f0ddb6308",
  "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0",
  "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
  "https://images.unsplash.com/photo-1501426026826-31c667bdf23d",
  "https://images.unsplash.com/photo-1581093588401-999ac1a1d4aa",
  "https://images.unsplash.com/photo-1517520287167-4bbf64a00d66",
  "https://images.unsplash.com/photo-1517430816045-df4b7de74b40",
  "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
  "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
  "https://images.unsplash.com/photo-1518770660439-4636190af475",
  "https://images.unsplash.com/photo-1542744173-8e7e53415bb0",
  "https://images.unsplash.com/photo-1581276879432-f7f1d35f5aa8",
  "https://images.unsplash.com/photo-1515169067869-d2a4d3b82db9",
  "https://images.unsplash.com/photo-1521747116042-5a810fda9664",
  "https://images.unsplash.com/photo-1508253578933-e2e4d219e5b5",
  "https://images.unsplash.com/photo-1519241047957-be31d7379a5d",
  "https://images.unsplash.com/photo-1504386106331-3e4e71712b38",
  "https://images.unsplash.com/photo-1522071820081-009f0129c71c",
  "https://images.unsplash.com/photo-1491897554428-130a60dd4757",
  "https://images.unsplash.com/photo-1511485977113-f5c98efef9d1",
  "https://images.unsplash.com/photo-1501426026826-31c667bdf23d",
  "https://images.unsplash.com/photo-1484101403633-562f891dc89a",
  "https://images.unsplash.com/photo-1506765515384-028b60a970df",
  "https://images.unsplash.com/photo-1542744173-8e7e53415bb0",
  "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
  "https://images.unsplash.com/photo-1518770660439-4636190af475",
  "https://images.unsplash.com/photo-1522202176988-66273c2fd55f",
  "https://images.unsplash.com/photo-1517430816045-df4b7de74b40",
  "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b",
  "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
  "https://images.unsplash.com/photo-1581093588401-999ac1a1d4aa",
  "https://images.unsplash.com/photo-1501426026826-31c667bdf23d",
  "https://images.unsplash.com/photo-1515169067869-d2a4d3b82db9",
  "https://images.unsplash.com/photo-1504386106331-3e4e71712b38",
  "https://images.unsplash.com/photo-1518770660439-4636190af475",
  "https://images.unsplash.com/photo-1542744173-8e7e53415bb0",
  "https://images.unsplash.com/photo-1581276879432-f7f1d35f5aa8",
  "https://images.unsplash.com/photo-1501426026826-31c667bdf23d",
  "https://images.unsplash.com/photo-1504384308090-c894fdcc538d",
  "https://images.unsplash.com/photo-1517520287167-4bbf64a00d66",
  "https://images.unsplash.com/photo-1501426026826-31c667bdf23d",
  "https://images.unsplash.com/photo-1498050108023-c5249f4df085",
  "https://images.unsplash.com/photo-1517520287167-4bbf64a00d66",
  "https://images.unsplash.com/photo-1506748686214-e9df14d4d9d0"
];

